# Generated by Django 2.1.4 on 2018-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectables',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
