# Generated by Django 2.1.4 on 2019-01-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injectable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField()),
                ('changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('order', models.TextField(null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcaserver.Scenario')),
            ],
        ),
        migrations.DeleteModel(
            name='Injectables',
        ),
        migrations.AddField(
            model_name='injectable',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcaserver.Scenario'),
        ),
    ]
