# Generated by Django 2.1.4 on 2018-12-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0002_injectables_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('order', models.TextField(null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcaserver.Scenarios')),
            ],
        ),
        migrations.AddField(
            model_name='injectables',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcaserver.Scenarios'),
        ),
    ]
