# Generated by Django 2.1.5 on 2019-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0004_scenario_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
