# Generated by Django 2.1.4 on 2018-12-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0004_carousel_carouselplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.TextField()),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='orcaserver.Carousel')),
            ],
        ),
    ]
