# Generated by Django 2.1.4 on 2018-12-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0003_auto_20181225_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='scenarios',
            name='sclist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcaserver.ScenarioList'),
        ),
    ]
