# Generated by Django 2.1.5 on 2019-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0006_injectable_can_be_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
