# Generated by Django 2.1.5 on 2019-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0007_auto_20190117_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectable',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
