# Generated by Django 2.2.4 on 2019-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0008_auto_20190121_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
