# Generated by Django 2.2.4 on 2019-10-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0009_step_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectable',
            name='docstring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='docstring',
            field=models.TextField(blank=True, null=True),
        ),
    ]
