# Generated by Django 2.2.4 on 2019-10-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0010_auto_20191011_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectable',
            name='module',
            field=models.TextField(blank=True, null=True),
        ),
    ]
