# Generated by Django 3.0.2 on 2020-01-23 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0011_injectable_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('module', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='module',
        ),
        migrations.AddField(
            model_name='injectable',
            name='groupname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeoProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orcaserver.Project')),
                ('srid', models.IntegerField()),
                ('bbox', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
            bases=('orcaserver.project',),
        ),
        migrations.AddField(
            model_name='scenario',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orcaserver.Project'),
            preserve_default=False,
        ),
    ]
