# Generated by Django 3.0 on 2020-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0013_injectable_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectable',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
