# Generated by Django 3.0 on 2020-02-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0016_injectable_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectable',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
