# Generated by Django 3.0.2 on 2020-11-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0021_logentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injectable',
            name='can_be_changed',
        ),
    ]
