# Generated by Django 2.1.4 on 2019-01-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0002_auto_20190104_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
