# Generated by Django 2.1.5 on 2019-01-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0003_auto_20190104_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='module',
            field=models.TextField(default=''),
        ),
    ]
