# Generated by Django 2.1.5 on 2019-01-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0005_auto_20190110_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectable',
            name='can_be_changed',
            field=models.BooleanField(default=True),
        ),
    ]
