# Generated by Django 3.0 on 2020-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0012_auto_20200123_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectable',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
