# Generated by Django 3.0.3 on 2020-02-10 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0018_injectable_data_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectable',
            name='parent_injectables',
            field=models.TextField(default='[]', validators=[django.core.validators.int_list_validator]),
        ),
    ]
