# Generated by Django 3.0.2 on 2020-11-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0020_auto_20201110_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('level', models.TextField(default='INFO')),
                ('timestamp', models.DateTimeField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcaserver.Scenario')),
            ],
        ),
    ]
