# Generated by Django 3.2.13 on 2023-03-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0024_injectable_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injectable',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='docstring',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='groupname',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='module',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='order',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='step',
            name='docstring',
        ),
    ]
