# Generated by Django 3.1.3 on 2021-02-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0025_remove_injectable_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injectable',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='docstring',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='groupname',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='module',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='order',
        ),
        migrations.RemoveField(
            model_name='injectable',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='step',
            name='docstring',
        ),
    ]
