# Generated by Django 4.1.7 on 2023-08-31 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcaserver', '0026_auto_20210224_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='OrcaDjango')),
                ('contact_mail', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('primary_color', models.CharField(default='#009688', max_length=30)),
                ('secondary_color', models.CharField(default='#e91e63', max_length=30)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenario_running_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenario_running_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenario_success_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenario_success_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenario_failed_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenario_failed_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('welcome_background_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('projects_background_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('scenarios_background_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('injectables_background_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('steps_background_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('welcome_text', models.TextField(blank=True, default='Willkommen', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('color', models.CharField(default='#FFFFFF', max_length=9)),
                ('settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
