# Generated by Django 4.1.7 on 2023-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0026_project_archived_project_code_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
