# Generated by Django 4.1.7 on 2023-08-31 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0027_sitesetting_project_archived_project_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('title', models.TextField(blank=True)),
                ('path', models.TextField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('init', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('preview_injectable', models.CharField(blank=True, max_length=80)),
                ('data_url', models.TextField(blank=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
