# Generated by Django 4.1.7 on 2023-09-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0028_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='data_url',
            new_name='info_html',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='init',
            new_name='init_injectables',
        ),
    ]
