# Generated by Django 4.1.7 on 2023-04-18 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def make_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model('orcaserver', 'Profile')
    profiles = [Profile(user=user) for user in User.objects.filter(profile=None)]
    Profile.objects.bulk_create(profiles)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcaserver', '0028_alter_project_code_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('color', models.CharField(default='#FFFFFF', max_length=9)),
                ('settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL))
            ],
        ),
        migrations.RunPython(make_profiles),
    ]
