# Generated by Django 4.1.7 on 2023-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0029_scenario_description_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='OrcaDjango')),
                ('contact_mail', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('primary_color', models.CharField(default='#009688', max_length=30)),
                ('secondary_color', models.CharField(default='#e91e63', max_length=30)),
                ('running_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('running_icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('welcome_background', models.ImageField(blank=True, null=True, upload_to='')),
                ('welcome_text', models.TextField(blank=True, default='Willkommen', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
