# Generated by Django 4.1.7 on 2023-04-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0029_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=9),
        ),
    ]
