# Generated by Django 4.1.7 on 2023-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0029_rename_data_url_module_info_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(default='black', max_length=9),
        ),
    ]
