# Generated by Django 4.1.7 on 2023-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0030_sitesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='running_icon',
            new_name='scenario_running_icon',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='running_image',
            new_name='scenario_running_image',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='scenario_failed_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='scenario_failed_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='scenario_success_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='scenario_success_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
