# Generated by Django 4.1.7 on 2023-09-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0031_avatar_remove_profile_icon_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='settings',
        ),
    ]
