# Generated by Django 4.1.7 on 2023-08-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0031_rename_running_icon_sitesetting_scenario_running_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='scenario_running_image',
            new_name='scenario_running_img',
        ),
    ]
