# Generated by Django 4.1.7 on 2024-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0032_remove_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_backgrounds',
            field=models.BooleanField(default=True),
        ),
    ]
