# Generated by Django 4.1.7 on 2023-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0032_rename_scenario_running_image_sitesetting_scenario_running_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='welcome_background',
            new_name='welcome_background_img',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='injectables_background_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='projects_background_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='scenarios_background_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='steps_background_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
