# Generated by Django 4.1.7 on 2024-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaserver', '0033_profile_show_backgrounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
